  ### CORNE START ###
    ### nice_view START ###
    # nice_nano_v2 + nice_epaper
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_epaper
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_View\"
    artifact-name: nice_corne_left_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_epaper
    artifact-name: nice_corne_right_view
